stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  tags:
    - javascript

deploy:
  stage: deploy
  environment:
    name: production
    url: "https://${NETLIFY_SITE_ID}.netlify.app"
  script:
    - npm run build
    - netlify deploy --prod --dir=build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
  tags:
    - javascript
  only:
    - tags
